#H2 Driver - POM Filen finns även.. Intern dataserver istället för MYSQL
#Lokal databas som körs direkt med Spring Boot

#spring.datasource.url=jdbc:h2:file:./data/villa-avougjagi-db
#spring.datasource.username=sa
#spring.datasource.password=


#H2-driver
#spring.datasource.driver-class-name=org.h2.Driver
#Hibernate skapar/uppdaterar tabeller från entities
#spring.jpa.hibernate.ddl-auto=update

#Visar SQL i IntelliJ-konsolen
#spring.jpa.show-sql=true

#H2-webbkonsol
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

#Gör att Thymeleaf ändringar syns direkt
#spring.thymeleaf.cache=false

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/Pensionatendb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false


